openapi: 3.0.0
info:
  version: 1.0.0
  title: Papet Gateway API
servers:
  - url: 'http://api.gateway.papet.balnis.eu/v1'

tags:
    - name: gateway-registration
    - name: client-binding
paths:
    /register-gateway:
        post:
            tags:
                - gateway-registration
            operationId: registerGateway
            summary: Register a new Papet gateway
            requestBody:
                $ref: '#/requestBodies/ManipulateGateway'

            responses:
                '200':
                    description: all good
                '400':
                    $ref: '#/responses/Error'
                '401':
                    $ref: '#/responses/Error'
                '403':
                    $ref: '#/responses/Error'
                default:
                    $ref: '#/responses/Error'

    /update-gateway:
        post:
            tags:
                - gateway-registration
            operationId: updateGateway
            summary: update an existing Papet gateway
            requestBody:
                $ref: '#/requestBodies/ManipulateGateway'
            responses:
                '200':
                    description: all good
                '400':
                    $ref: '#/responses/Error'
                '401':
                    $ref: '#/responses/Error'
                '403':
                    $ref: '#/responses/Error'
                default:
                    $ref: '#/responses/Error'

    /connection-created:
        post:
            tags:
                - client-binding
            operationId: connectionCreated
            requestBody:
                content:
                    'application/json':
                        schema:
                            allOf:
                                -   type: object
                                    required:
                                        - clientId
                                        - clientSecret
                                    properties:
                                        # authentication
                                        clientId:
                                            type: string
                                        clientSecret:
                                            type: string
                                        # authorization
                                        nonce:
                                            type: string
                                        # payload
                                -   oneOf:
                                        -   type: object
                                            required:
                                                - externalClientName
                                            properties:
                                                externalClientName:
                                                    type: string
                                        -   type: object
                                            required:
                                                - failure
                                            properties:
                                                failure:
                                                    type: string
                                                    enum:
                                                        - rejected
                                                        - timeout
                                                        - other
            responses:
                '200':
                    description: all good
                '400':
                    $ref: '#/responses/Error'
                '401':
                    $ref: '#/responses/Error'
                '403':
                    $ref: '#/responses/Error'
                default:
                    $ref: '#/responses/Error'

components:
    schemas:
        TypeOfWork:
            description: structured data packed into a string, see documentation
            type: string
    requestBodies:
        ManipulateGateway:
            content:
                'application/json':
                    schema:
                        type: object
                        required:
                            - clientId
                            - clientSecret
                            - restEndpoint
                            - requiresBrowserOnCreate
                        properties:
                            # authentication
                            clientId:
                                type: string
                            clientSecret:
                                type: string
                            # payload
                            restEndpoint:
                                type: string
                            requiresBrowserOnCreate:
                                type: boolean
                            icon:
                                description: image is passed as base64-encoded binary entity, see documentation
                                type: string
                            typesofwork:
                                type: array
                                items:
                                    $ref: '#/schemas/TypeOfWork'
                            targets:
                                type: array
                                items:
                                    type: object
                                    required: 
                                        - id
                                        - texts
                                    properties:
                                        id:
                                            description: there are restictions to what the string values might be, see documentation
                                            type: string
                                        typeofwork:
                                            $ref: '#/schemas/TypeOfWork'
                                        texts:
                                            type: array
                                            minItems: 1
                                            items:
                                                type: object
                                                required: 
                                                    - language
                                                    - label
                                                properties:
                                                    language:
                                                        description: ISO 639-1 lang code
                                                        type: string
                                                    label:
                                                        type: string

    responses:
        Error:
            description: general purpose error
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            error:
                                type: string
